# Generated by Django 5.1.1 on 2024-09-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.IntegerField()),
                ('cover', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
